ALTER TABLE EMPLOYEES
DROP (PHOTOPATH, REPORTSTO, NOTES);

ALTER TABLE PRODUCTS
DROP CONSTRAINT SUPPLIERS_FK;
ALTER TABLE SUPPLIERS
DROP CONSTRAINT SUPPLIERS_PK;
ALTER TABLE SUPPLIERS
ADD CONSTRAINT PHONE_PK PRIMARY KEY (PHONE);

ALTER TABLE CUSTOMER
ADD IS_ACTIVE NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE CATEGORIES
MODIFY PICTURE NVARCHAR2(100);

CREATE SEQUENCE MY_FIRST_SEQUENCE
    START WITH 1
    INCREMENT BY 3;
