SELECT DIRECTOR, COUNT(*)
FROM MOVIE
GROUP BY DIRECTOR;


SELECT  DIRECTOR,
        SUM(domestic_sales) domestic_sales,
        SUM(international_sales) international_sales
FROM    MOVIE, MOVIE_STAT
WHERE   MOVIE.ID = MOVIE_STAT.MOVIE_ID
GROUP BY DIRECTOR




SELECT *
FROM MOVIE
ORDER BY YEAR DESC;

SELECT *
FROM MOVIE_STAT
ORDER BY INTERNATIONAL_SALES DESC;