CREATE TABLE ORDERS(
    ID NUMBER,
    CONSTRAINT ORDER_ID PRIMARY KEY(ID),
    PRODUCT_NAME NVARCHAR2(20),
    PRICE NUMBER,
    DATE_ORDERED TIMESTAMP,
    DATE_CONFIRMED TIMESTAMP
);

--lesson4
CREATE TABLE ORDERS (
    ID NUMBER CHECK(ID <= 10000),
    CONSTRAINT ORDER_ID PRIMARY KEY(ID),
    USER_ID NUMBER,
    ROOM_ID NUMBER,
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID DECIMAL(10, 2)
)


