SELECT DIRECTOR, COUNT(ID)
FROM MOVIE
GROUP BY DIRECTOR;


SELECT m.DIRECTOR, SUM(ms.DOMESTIC_SALES), SUM(ms.INTERNATIONAL_SALES)
FROM MOVIE m
LEFT JOIN MOVIE_STAT ms ON m.ID = ms.MOVIE_ID
GROUP BY m.DIRECTOR;




SELECT *
FROM MOVIE
ORDER BY YEAR DESC;

SELECT *
FROM MOVIE_STAT
ORDER BY INTERNATIONAL_SALES DESC;