SELECT	CUSTOMER.CUSTNAME, 
		CUSTOMER.CITY, 
		SALESMAN.NAME, 
		SALESMAN.CITY
FROM	DEAL
    JOIN CUSTOMER ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
    LEFT JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
WHERE	DEAL.AMOUNT > 10000;


SELECT	CUSTOMER.CUSTNAME, 
		CUSTOMER.CITY
FROM	CUSTOMER
WHERE	EXISTS (
	SELECT	* 
	FROM	DEAL 
	WHERE	DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID 
			AND EXTRACT(YEAR FROM DEAL.DATE_DEAL) IN (2017,2018)
);


SELECT	CUSTOMER.CUSTNAME, 
		SUM(DEAL.AMOUNT)
FROM	DEAL
	LEFT JOIN CUSTOMER ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE	EXTRACT(YEAR FROM DEAL.DATE_DEAL) = 2017
		AND EXTRACT(MONTH FROM DEAL.DATE_DEAL) = 8
GROUP BY CUSTOMER.CUSTNAME
HAVING	SUM(DEAL.AMOUNT) >= ALL(
			SELECT	SUM(AMOUNT) FROM DEAL
			WHERE	EXTRACT(YEAR FROM DATE_DEAL) = 2017
					AND EXTRACT(MONTH FROM DATE_DEAL) = 8 
			GROUP BY CUSTOMER_ID
);